### ISSUE TITLE
Volumeslider problem and restoreVolume question

### ISSUE THREAD

**Issue by Overland-DX** [AmateurAudioDude/FM-DX-Webserver-Plugin-Frequency-Volume-Reduction#1]
Hi

If you have reduced the volume with the slider, the volume goes up to maximum when I change the frequency.

And is it possible to set a timer on "restoreVolume();" In line: 27?
Because the sound is reset to maximum before the sound stream has had time to change, when you go from a frequency that has sound reduction to a frequency that does not have sound reduction. I also notice it easily when I use the ButtonPresets plugin and then when I switch from a station that has sound reduction to one that doesn't.

By the way, thank you very much for a useful plugin. This is perfect for us who live in Norway.

**Comment by Overland-DX** [comment]
I moved - if (Stream) { Stream.Volume = valueStreamVolume; }
In line: 84 and put it after line: 95

Like this:

            tunerDesc.style.cursor = 'auto';
		if (Stream) { Stream.Volume = valueStreamVolume; }
        }, 500);

It seems to be working.

**Comment by AmateurAudioDude** [comment]
Thanks for the tip, it definitely benefits from having a delay.

**Comment by Overland-DX** [comment]
Just pleasant. 
I have set up my plugin as follows:
 if (valueFrequency.some(freq => dataFrequency >= (freq - 0.095) && dataFrequency <= (freq + 0.095))) {
To mute only the current frequency. Since I have no problems with noise on the side frequencies on my server.
And I increased the delay from 500 to 700 milliseconds. 800 ms is perhaps even better.
I am super happy with this plugin now.
The only problem I still have is that the volume slider no longer works when I change the frequency. If I set it to 20% volume, it is reset to 100% every time I change the frequency.

**Comment by Overland-DX** [comment]
I see you have already updated the plugin, I have tested and it works fine. I think 800ms is perfect delay.
Slider still doesn't work here.

**Comment by AmateurAudioDude** [comment]
There's another update. Looks like some recent changes to the way the volume operates meant I had to make some changes on my end. It should be ok now.

**Comment by Overland-DX** [comment]
Amazing! Now it works perfectly :) Thank you very much for taking the time.
